# .NET Desktop
# https://docs.microsoft.com/azure/devops/pipelines/apps/windows/dot-net

name: $(Date:yyyyMMdd).$(Rev:.r) 

variables:
  win-solution: 'DevAudit.sln'
  linux-solution: 'DevAudit.Mono.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'RuntimeDebug'

jobs:
- job: Windows
  pool:
    vmImage: 'VS2017-Win2016'
  steps:
  - script: $(Build.SourcesDirectory)/build.cmd /p:VersionAssembly=$(releaseVersion)

- job: Linux
  pool:
    vmImage: 'ubuntu-16.04'
  steps:
  - script: $(Build.SourcesDirectory)/build.sh /p:VersionAssembly=$(releaseVersion)
